os: windows
language: ruby
install:
- bundle install
before_script:
- sudo apt-get install ditaa
- chmod +x build.sh
script: "./build.sh"
branches:
  only:
  - jekyll
  notifications:
  email:
    recipients:
    - yusufkaratoprak@gmail.com
    - admin@yusufkaratoprak.com
    on_success: never
    on_failure: always